import { useState } from "react";
import { X, FileJson } from "lucide-react";
import { ViTrackData } from "@/types";

interface AddPathwayModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAdd: (data: ViTrackData) => void;
}

export default function AddPathwayModal({ isOpen, onClose, onAdd }: AddPathwayModalProps) {
  const [jsonInput, setJsonInput] = useState("");
  const [error, setError] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const parsed = JSON.parse(jsonInput) as ViTrackData;
      // Basic validation check
      if (!parsed.track_id || !parsed.title || !parsed.milestones) {
        throw new Error("Invalid schema: Missing required Vi Track fields.");
      }
      onAdd(parsed);
      setJsonInput("");
      setError(null);
      onClose();
    } catch (err: any) {
      setError(err.message || "Invalid JSON format");
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-2xl overflow-hidden flex flex-col max-h-[90vh]">
        <div className="flex justify-between items-center p-5 border-b border-gray-100">
          <div className="flex items-center space-x-2">
            <div className="bg-emerald-100 text-emerald-700 p-2 rounded-lg">
              <FileJson className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-bold text-gray-900">Add New Pathway</h2>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 p-1 rounded-md transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-5 flex-1 flex flex-col overflow-y-auto">
          <p className="text-sm text-gray-600 mb-4">
            Paste the JSON output generated by Vi Nav here. The system will automatically parse and create your collaborative Vi Track dashboard.
          </p>
          
          <textarea
            value={jsonInput}
            onChange={(e) => setJsonInput(e.target.value)}
            className="w-full flex-1 min-h-[300px] p-4 font-mono text-sm bg-slate-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none resize-none"
            placeholder="{\n  &quot;track_id&quot;: &quot;...&quot;,\n  &quot;title&quot;: &quot;...&quot;\n}"
          />
          
          {error && (
            <div className="mt-3 p-3 bg-red-50 text-red-700 text-sm rounded-lg border border-red-100">
              {error}
            </div>
          )}

          <div className="mt-6 flex justify-end space-x-3">
            <button 
              type="button" 
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 rounded-lg transition-colors border border-transparent"
            >
              Cancel
            </button>
            <button 
              type="submit"
              className="px-5 py-2 text-sm font-medium text-white bg-emerald-600 hover:bg-emerald-700 rounded-lg shadow-sm transition-colors"
            >
              Import Pathway
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
