-- Create the tracks table
-- This stores the core pathway data generated by the AI (milestones, tasks, resources) as JSONB
CREATE TABLE tracks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    description TEXT,
    category TEXT,
    overall_progress_percentage NUMERIC DEFAULT 0,
    content JSONB NOT NULL, -- The unstructured but validated JSON from Vi Nav
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create the collaborators table
-- This manages role-based access to the tracks
CREATE TABLE collaborators (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    track_id UUID NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('owner', 'member', 'admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(track_id, user_id)
);

-- Create the daily_logs table
-- High-frequency data stored relationally for easy querying and charting
CREATE TABLE daily_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    track_id UUID NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    mood_rating INTEGER CHECK (mood_rating >= 1 AND mood_rating <= 5),
    notes TEXT,
    high_importance BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) POLICIES
-------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE collaborators ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_logs ENABLE ROW LEVEL SECURITY;

-- 1. Tracks Policies
-- Users can SELECT a track if they are listed as a collaborator
CREATE POLICY "Users can view tracks they collaborate on"
ON tracks FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM collaborators
        WHERE collaborators.track_id = tracks.id
        AND collaborators.user_id = auth.uid()
    )
);

-- Users can UPDATE a track if they are listed as a collaborator
CREATE POLICY "Users can update tracks they collaborate on"
ON tracks FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM collaborators
        WHERE collaborators.track_id = tracks.id
        AND collaborators.user_id = auth.uid()
    )
);

-- Only owners can delete tracks (defined in collaborators)
CREATE POLICY "Only owners can delete tracks"
ON tracks FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM collaborators
        WHERE collaborators.track_id = tracks.id
        AND collaborators.user_id = auth.uid()
        AND collaborators.role = 'owner'
    )
);

-- 2. Collaborators Policies
-- Users can see other collaborators on a track they have access to
CREATE POLICY "Users can view collaborators on their tracks"
ON collaborators FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM collaborators AS c
        WHERE c.track_id = collaborators.track_id
        AND c.user_id = auth.uid()
    )
);

-- Only owners/admins can invite new collaborators
CREATE POLICY "Owners can add new collaborators"
ON collaborators FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM collaborators
        WHERE collaborators.track_id = track_id
        AND collaborators.user_id = auth.uid()
        AND collaborators.role IN ('owner', 'admin')
    )
);

-- 3. Daily Logs Policies
-- Users can view logs for a track if they are a collaborator
CREATE POLICY "Users can view logs for their tracks"
ON daily_logs FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM collaborators
        WHERE collaborators.track_id = daily_logs.track_id
        AND collaborators.user_id = auth.uid()
    )
);

-- Any collaborator can insert a daily log
CREATE POLICY "Collaborators can add daily logs"
ON daily_logs FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM collaborators
        WHERE collaborators.track_id = track_id
        AND collaborators.user_id = auth.uid()
    )
    AND user_id = auth.uid() -- Ensure they are logging as themselves
);

-- Users can only delete their own logs
CREATE POLICY "Users can delete their own logs"
ON daily_logs FOR DELETE
USING (user_id = auth.uid());
